import 'package:equatable/equatable.dart';

import 'jobs.dart';

class AutoGeneratedJob extends Equatable {
  //this entities to controll
  final bool error;
  final String search;
  final int page;
  final int limit;
  final int total;
  final List<String> skills;
  final List<Jobs> jobs;

  const AutoGeneratedJob(this.error, this.search, this.page, this.limit,
      this.total, this.skills, this.jobs);

  @override
  List<Object?> get props => [
        error,
        search,
        page,
        limit,
        total,
        skills,
        jobs,
      ];
}
